/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.algoritmoQAP;
import Modelo.algoritmoSA;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JONATHAN ESCOBAR
 */
public class FrmMain extends javax.swing.JFrame {

    algoritmoQAP aQAP;
    algoritmoSA aSA;

    public FrmMain() {
        initComponents();
        this.setLocationRelativeTo(this);
        aSA = new algoritmoSA();
        aQAP = new algoritmoQAP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtArUrl = new javax.swing.JTextField();
        btnArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDistancia = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFlujo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNUno = new javax.swing.JTextField();
        txtNDos = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        txtDisminuirT = new javax.swing.JTextField();
        btnEjecutar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCosto = new javax.swing.JLabel();
        lblPermutacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Captura de Datos");

        txtArUrl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtArUrl.setEnabled(false);
        txtArUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArUrlActionPerformed(evt);
            }
        });

        btnArchivo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnArchivo.setText("Archivo");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        tblDistancia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblDistancia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDistancia);

        tblFlujo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblFlujo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblFlujo);

        jLabel2.setText("N1: ");

        jLabel3.setText("N2: ");

        jLabel4.setText("T: ");

        jLabel5.setText("Disminuir T: ");

        txtNUno.setText("1000");

        txtNDos.setText("500");

        txtTemperatura.setText("10000");

        txtDisminuirT.setText("0.95");

        btnEjecutar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCosto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCosto.setText("0.0");

        lblPermutacion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblPermutacion.setText("[][][]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCosto)
                    .addComponent(lblPermutacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCosto)
                .addGap(7, 7, 7)
                .addComponent(lblPermutacion)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEjecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArUrl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNUno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(txtNDos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTemperatura)
                                    .addComponent(txtDisminuirT, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArchivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtNUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtNDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisminuirT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEjecutar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        JFileChooser fC = new JFileChooser();
        int option = fC.showOpenDialog(this);
        int a = 0;
        if ((a = this.tblDistancia.getRowCount()) > 0) {
            for (int i = a - 1; i >= 0; i--) {
                DefaultTableModel mD = (DefaultTableModel) tblDistancia.getModel();
                mD.removeRow(i);
                DefaultTableModel mF = (DefaultTableModel) tblFlujo.getModel();
                mF.removeRow(i);
            }
        }
        if (option == JFileChooser.APPROVE_OPTION) {
            try {
                this.txtArUrl.setText(fC.getSelectedFile().getPath());
                BufferedReader bR = new BufferedReader(new FileReader(fC.getSelectedFile().getPath()));
                String ln = "";
                String datos[];
                int aux = 0;
                int count = 0;
                int[][] mFlujo = new int[0][0];
                int[][] mDistancia = new int[0][0];
                while ((ln = bR.readLine()) != null) {
                    datos = ln.split(" ");
                    if (count == 0) {// creamos la tabla nxn tanto de distancia como de flujo
                        DefaultTableModel modelo = (DefaultTableModel) tblDistancia.getModel();
                        modelo.setColumnCount(datos.length);
                        DefaultTableModel modeloF = (DefaultTableModel) tblFlujo.getModel();
                        modeloF.setColumnCount(datos.length);
                        mFlujo = new int[datos.length][datos.length];
                        mDistancia = new int[datos.length][datos.length];
                    }
                    if (ln.equals("-") || aux > 0) {
                        aux++;
                    }
                    if (aux == 0) {
                        DefaultTableModel modelo = (DefaultTableModel) tblDistancia.getModel();
                        modelo.addRow(datos);
                    } else if (aux > 1) {
                        DefaultTableModel modelo = (DefaultTableModel) tblFlujo.getModel();
                        modelo.addRow(datos);

                    }
                    count++;
                }
                for (int i = 0; i < tblDistancia.getRowCount(); i++) {
                    for (int j = 0; j < tblDistancia.getColumnCount(); j++) {
                        mDistancia[i][j] = Integer.parseInt(tblDistancia.getValueAt(i, j) + "");
                        System.out.print("[" + tblDistancia.getValueAt(i, j) + "]");
                    }
                    System.out.println();
                }
                System.out.println("----------");
                for (int i = 0; i < tblFlujo.getRowCount(); i++) {
                    for (int j = 0; j < tblFlujo.getColumnCount(); j++) {
                        mFlujo[i][j] = Integer.parseInt(tblFlujo.getValueAt(i, j) + "");
                        System.out.print("[" + tblFlujo.getValueAt(i, j) + "]");
                    }
                    System.out.println();
                }
                aSA.setmDistancia(mDistancia);
                aSA.setmFlujo(mFlujo);
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        String res = aSA.SimulatedAnnealing(Integer.parseInt(txtNUno.getText()), Integer.parseInt(txtNDos.getText()), Integer.parseInt(txtTemperatura.getText()), Double.parseDouble(txtDisminuirT.getText()));
        String[] datos = res.split(" ");
        this.lblCosto.setText("Costo: " + datos[0]);
        this.lblPermutacion.setText("Permutacion: " + datos[1]);
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void txtArUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArUrlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblPermutacion;
    private javax.swing.JTable tblDistancia;
    private javax.swing.JTable tblFlujo;
    private javax.swing.JTextField txtArUrl;
    private javax.swing.JTextField txtDisminuirT;
    private javax.swing.JTextField txtNDos;
    private javax.swing.JTextField txtNUno;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
